#!/bin/sh -e

# debirf module: bootlog
# configure bootlog
#
# The debirf scripts were written by
# Jameson Rollins <jrollins@fifthhorseman.net>
# and
# Daniel Kahn Gillmor <dkg@fifthhorseman.net>.
#
# They are Copyright 2007, and are all released under the GPL,
# version 3 or later.

cat <<EOF > "$DEBIRF_ROOT"/etc/default/bootlogd
# Run bootlogd at startup ?
BOOTLOGD_ENABLE=Yes
EOF
