#!/bin/bash -e

# debirf module: install-manpages
#
# The debirf scripts were written by
# Jameson Rollins <jrollins@fifthhorseman.net>
# and
# Daniel Kahn Gillmor <dkg@fifthhorseman.net>.
#
# They are Copyright 2007, and are all released under the GPL,
# version 3 or later.

debirf_exec apt-get --assume-yes install man-db manpages info
