#!/bin/bash -e

# debirf module: rescue
# remove/install extra packages for rescue environment
#

# install packages
debirf_exec apt-get --no-install-recommends --assume-yes install \
 bash-completion \
 bind9utils \
 build-essential \
 byobu \
 dnsutils \
 expect \
 git \
 htop \
 iftop \
 iotop \
 iptraf \
 libwww-perl \
 mercurial \
 netcat \
 netcat-traditional \
 nmap \
 ntp \
 openssh-server \
 python-pycurl \
 screen \
 ssl-cert \
 subversion \
 sudo \
 sysstat \
 tcptraceroute \
 telnet \
 tmux \
 traceroute \
 unzip \
 uuid \
 vim-nox \
 zsh \
 zsh-static
